"""
checklist_render.py

Validate and render the AI4R machine-checkable checklists.

Drives two YAML sources of truth:
  - `checklist.yaml`     — reproducibility rubric (BJ + audit items)
  - `cqv_checklist.yaml` — CQV code-quality rubric

For each YAML, the schema file is `<basename>.schema.json` and the rendered
Markdown view is `<UPPER_BASENAME>.md` (e.g. `CHECKLIST.md`, `CQV_CHECKLIST.md`).

Usage:
    python -m tools.checklist_render
        # Validates + renders the default reproducibility checklist.

    python -m tools.checklist_render --yaml cqv_checklist.yaml
        # Validates + renders the CQV checklist.

    python -m tools.checklist_render --validate
        # Validate only.

    python -m tools.checklist_render --check
        # Validate + verify on-disk Markdown is in sync; exit 1 if not.

    python -m tools.checklist_render --all
        # Process every *checklist.yaml file at the repo root.

Dependencies:
    pip install pyyaml jsonschema
"""

from __future__ import annotations

import argparse
import difflib
import json
import sys
from pathlib import Path
from typing import Any

import yaml
from jsonschema import Draft202012Validator

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_YAML = REPO_ROOT / "checklist.yaml"


# ---------------------------------------------------------------------------
# Path derivation
# ---------------------------------------------------------------------------

def derive_paths(yaml_path: Path) -> tuple[Path, Path]:
    """Given a YAML path, return its schema and rendered-Markdown paths.

    Convention:
        ``checklist.yaml``       → ``checklist.schema.json``,     ``CHECKLIST.md``
        ``cqv_checklist.yaml``   → ``cqv_checklist.schema.json``, ``CQV_CHECKLIST.md``
    """
    yaml_path = yaml_path.resolve()
    schema_path = yaml_path.with_suffix(".schema.json")
    md_path = yaml_path.parent / (yaml_path.stem.upper() + ".md")
    return schema_path, md_path


# ---------------------------------------------------------------------------
# Loading and validation
# ---------------------------------------------------------------------------

def load_yaml(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def load_schema(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def validate_against_schema(data: dict[str, Any], schema: dict[str, Any]) -> list[str]:
    """Return a list of schema validation errors as readable strings."""
    validator = Draft202012Validator(schema)
    errors = sorted(validator.iter_errors(data), key=lambda e: list(e.path))
    return [
        f"{'/'.join(str(p) for p in e.absolute_path) or '<root>'}: {e.message}"
        for e in errors
    ]


def cross_check(data: dict[str, Any]) -> list[str]:
    """Schema-independent invariants applicable to both checklist flavors."""
    errors: list[str] = []

    # Unique item ids.
    ids: set[str] = set()
    for item in data["items"]:
        if item["id"] in ids:
            errors.append(f"duplicate item id: {item['id']}")
        ids.add(item["id"])

    valid_categories = {c["id"] for c in data["categories"]}
    for item in data["items"]:
        if item["category"] not in valid_categories:
            errors.append(f"{item['id']}: unknown category '{item['category']}'")

    # Reproducibility-specific: parent must resolve to a BJ item.
    bj_ids = {item["id"] for item in data["items"] if item.get("source") == "bj_essential"}
    if bj_ids:  # only enforced when the YAML uses the BJ source convention
        for item in data["items"]:
            parent = item.get("parent")
            if parent and parent not in bj_ids:
                errors.append(f"{item['id']}: parent '{parent}' does not resolve to a BJ item")

    return errors


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

CHECK_TYPE_BADGE = {"static": "🔧 static", "dynamic": "▶ dynamic", "llm": "🧠 llm"}


def _render_header(data: dict[str, Any], title: str) -> list[str]:
    lines = [
        "<!-- DO NOT EDIT BY HAND. -->",
        "<!-- This file is generated by tools/checklist_render.py. -->",
        "",
        f"# {title}",
        "",
        f"_Version {data['version']} — last updated {data['last_updated']}_",
        "",
    ]
    if "source" in data:
        lines += [f"_Source: {data['source']}_", ""]
    if "notes" in data:
        lines += [data["notes"], ""]
    return lines


def _render_items(data: dict[str, Any]) -> list[str]:
    """Render every item, grouped by category in declaration order."""
    lines: list[str] = []
    items_by_category: dict[str, list[dict[str, Any]]] = {
        c["id"]: [] for c in data["categories"]
    }
    for item in data["items"]:
        items_by_category[item["category"]].append(item)

    for cat in data["categories"]:
        cat_items = items_by_category[cat["id"]]
        if not cat_items:
            continue
        lines += [f"## {cat['name']}", ""]

        # Sort: BJ items first if present, then audit items grouped under
        # parent. For CQV YAML (no BJ items) this collapses to id sort.
        bj_items = sorted(
            [i for i in cat_items if i.get("source") == "bj_essential"],
            key=lambda i: i["id"],
        )
        audit_items = sorted(
            [i for i in cat_items if i.get("source") == "audit_extended"],
            key=lambda i: (i.get("parent", ""), i["id"]),
        )
        other_items = sorted(
            [i for i in cat_items if "source" not in i],
            key=lambda i: i["id"],
        )

        for it in bj_items + audit_items + other_items:
            badge = CHECK_TYPE_BADGE[it["check_type"]]
            sev = it["severity"].upper()
            applies = ", ".join(it["applies_to"])
            extras = []
            if it.get("parent"):
                extras.append(f"refines `{it['parent']}`")
            if it.get("cross_reference"):
                extras.append(f"see also `{it['cross_reference']}`")
            extras_str = f" _({'; '.join(extras)})_" if extras else ""

            lines += [
                f"### `{it['id']}` — {sev} · {badge} · applies to: {applies}{extras_str}",
                "",
                f"- [ ] {it['description'].strip()}",
                "",
                f"  **tool**: `{it['tool_id']}`",
                "",
                "  **evidence required**:",
            ]
            for ev in it["evidence_required"]:
                lines.append(f"  - {ev}")
            lines.append("")
    return lines


def _render_also_enforces(data: dict[str, Any]) -> list[str]:
    block = data.get("also_enforces")
    if not block:
        return []
    lines = [
        "## Cross-references (items run on behalf of the reproducibility checklist)",
        "",
        (
            "The CQV agent runs these items from `checklist.yaml` and emits the "
            "resulting evidence in `cqv_output.json`. The Review agent reads it "
            "directly rather than re-running these checks."
        ),
        "",
    ]
    for entry in block:
        lines.append(f"- **`{entry['id']}`** — {entry['note']}")
    lines.append("")
    return lines


def _render_scoring(data: dict[str, Any]) -> list[str]:
    block = data.get("scoring")
    if not block:
        return []
    lines = ["## Scoring", "", f"**Formula**: `{block['formula']}`", ""]
    if "notes" in block:
        lines += [block["notes"], ""]
    lines += ["| Score | Classification | Action |", "|---|---|---|"]
    for band in block["bands"]:
        lines.append(f"| {band['range']} | {band['classification']} | {band['action']} |")
    lines.append("")
    return lines


def _render_legends(data: dict[str, Any]) -> list[str]:
    lines = ["---", "", "## Severity legend", ""]
    for s in data["severities"]:
        lines.append(f"- **{s['id'].upper()}** — {s['description']}")
    lines += ["", "## Check-type legend", ""]
    for ct in data["check_types"]:
        lines.append(f"- **{CHECK_TYPE_BADGE[ct['id']]}** — {ct['description']}")
    lines.append("")
    return lines


def render_markdown(data: dict[str, Any], yaml_path: Path) -> str:
    """Build the human-readable Markdown view from the YAML data."""
    stem = yaml_path.stem
    if stem == "checklist":
        title = "AI4Reproducibility — Essential Reproducibility Checklist"
    elif stem == "cqv_checklist":
        title = "AI4Reproducibility — CQV Code-Quality Checklist"
    else:
        title = f"AI4Reproducibility — {stem.replace('_', ' ').title()}"

    sections = (
        _render_header(data, title)
        + _render_also_enforces(data)
        + _render_scoring(data)
        + _render_items(data)
        + _render_legends(data)
    )
    return "\n".join(sections)


# ---------------------------------------------------------------------------
# Per-file driver
# ---------------------------------------------------------------------------

def process_one(yaml_path: Path, *, do_validate: bool, do_render: bool, do_check: bool) -> int:
    """Process a single YAML file. Returns a process exit code."""
    schema_path, md_path = derive_paths(yaml_path)

    if not yaml_path.exists():
        print(f"error: YAML not found: {yaml_path}", file=sys.stderr)
        return 2
    if not schema_path.exists():
        print(f"error: schema not found: {schema_path}", file=sys.stderr)
        return 2

    data = load_yaml(yaml_path)
    schema = load_schema(schema_path)

    if do_validate:
        errs = validate_against_schema(data, schema) + cross_check(data)
        if errs:
            print(f"VALIDATION FAILED — {yaml_path.name}", file=sys.stderr)
            for e in errs:
                print(f"  - {e}", file=sys.stderr)
            return 1
        print(f"{yaml_path.name}: OK ({len(data['items'])} items)")

    rendered = render_markdown(data, yaml_path)

    if do_check:
        existing = md_path.read_text(encoding="utf-8") if md_path.exists() else ""
        if existing != rendered:
            print(f"DRIFT: {md_path.name} is not in sync with {yaml_path.name}.", file=sys.stderr)
            diff = difflib.unified_diff(
                existing.splitlines(keepends=True),
                rendered.splitlines(keepends=True),
                fromfile=str(md_path),
                tofile="(regenerated)",
            )
            sys.stderr.writelines(diff)
            return 1
        print(f"{md_path.name}: in sync with {yaml_path.name}")

    if do_render:
        md_path.write_text(rendered, encoding="utf-8")
        print(f"wrote {md_path.relative_to(REPO_ROOT)}")

    return 0


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--yaml",
        type=Path,
        default=DEFAULT_YAML,
        help="Path to the checklist YAML (default: %(default)s).",
    )
    parser.add_argument(
        "--all",
        action="store_true",
        help="Process every *checklist.yaml at the repo root.",
    )
    parser.add_argument("--validate", action="store_true", help="Validate only.")
    parser.add_argument("--render", action="store_true", help="Render only.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Validate + verify the on-disk Markdown is in sync. Exit 1 if not.",
    )
    args = parser.parse_args()

    # Default behaviour (no mode flag): validate AND render.
    any_mode = args.validate or args.render or args.check
    do_validate = args.validate or args.check or not any_mode
    do_render = args.render or not any_mode
    do_check = args.check

    if args.all:
        targets = sorted(REPO_ROOT.glob("*checklist.yaml"))
        if not targets:
            print("no *checklist.yaml files found at repo root", file=sys.stderr)
            return 2
    else:
        targets = [args.yaml]

    overall = 0
    for target in targets:
        rc = process_one(
            target,
            do_validate=do_validate,
            do_render=do_render,
            do_check=do_check,
        )
        overall = max(overall, rc)
    return overall


if __name__ == "__main__":
    sys.exit(main())
